/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author danielalvarado
 */
public class HistFrame extends javax.swing.JFrame {

    /**
     * Creates new form HistFrame
     */
    public HistFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        empleadoRadioBtn = new javax.swing.JRadioButton();
        tiempoRadioBtn = new javax.swing.JRadioButton();
        plantaRadioBtn = new javax.swing.JRadioButton();
        mostarBtn = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historico");

        buttonGroup1.add(empleadoRadioBtn);
        empleadoRadioBtn.setText("Por Empleado");
        empleadoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(tiempoRadioBtn);
        tiempoRadioBtn.setText("Por Periodo de Tiempo");

        buttonGroup1.add(plantaRadioBtn);
        plantaRadioBtn.setText("Por Planta");
        plantaRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantaRadioBtnActionPerformed(evt);
            }
        });

        mostarBtn.setText("Mostrar");
        mostarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostarBtnMouseClicked(evt);
            }
        });

        jButton1.setText("<-");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tiempoRadioBtn)
                            .addComponent(plantaRadioBtn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoRadioBtn, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(mostarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(empleadoRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiempoRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostarBtn)
                    .addComponent(plantaRadioBtn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoRadioBtnActionPerformed

    private void plantaRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantaRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantaRadioBtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void mostarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostarBtnMouseClicked

        // TODO add your handling code here:
        if (empleadoRadioBtn.isSelected()) {
            new HistEmpleadoDialog(this,true).setVisible(true);
        } else if (tiempoRadioBtn.isSelected()) {
            new HistTiempoDialog(this,true).setVisible(true);
        }else if (plantaRadioBtn.isSelected()) {
            new HistPlantaDialog(this,true).setVisible(true);
        }
    }//GEN-LAST:event_mostarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton empleadoRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton mostarBtn;
    private javax.swing.JRadioButton plantaRadioBtn;
    private javax.swing.JRadioButton tiempoRadioBtn;
    // End of variables declaration//GEN-END:variables
}
