/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import static Frames.EmpAscDialog.Type;
import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import printer.PDFprinter;
import util.PlantInfo;
import util.Query ;

/**
 *
 * @author danielalvarado
 */
public class PagosPlanillasDialog extends javax.swing.JDialog {

    /**
     * Creates new form HistPlantaDialog
     */
    public PagosPlanillasDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pagarBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePlanillas = new javax.swing.JTable();
        backPagosBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        plaNumTextEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Planta: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Pago pendientes:");

        pagarBTN.setText("Pagar");
        pagarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarBTNMouseClicked(evt);
            }
        });
        pagarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBTNActionPerformed(evt);
            }
        });

        jTablePlanillas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTablePlanillas);

        backPagosBTN.setText("<-");
        backPagosBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPagosBTNMouseClicked(evt);
            }
        });

        jLabel3.setText("Numero de Planilla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backPagosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plaNumTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pagarBTN)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(backPagosBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagarBTN)
                    .addComponent(jLabel3)
                    .addComponent(plaNumTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarBTNActionPerformed

    private void backPagosBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPagosBTNMouseClicked
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_backPagosBTNMouseClicked
    
    private JTable getSelectedTable(JTable tabla, int selectedPlanilla){
        
        JTable tablaResultado = new JTable();

        Vector<String> columnNames = new Vector<String>();
        int columnCount = tabla.getColumnCount();
        for (int column = 0; column < columnCount; column++) {
            columnNames.add(tabla.getColumnName(column));
        }
        
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        //Vector<String> data = new Vector<String>();
        
        int size = 0;
        
        while (size < tabla.getRowCount()) {
            //System.out.println("Jjeje");
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
                if ((int)tabla.getValueAt(size, 0) == selectedPlanilla){
                    vector.add(tabla.getValueAt(size, columnIndex));
                }
            }
            size++;
            data.add(vector);
        }
        
        tablaResultado.setModel(new DefaultTableModel(data, columnNames));
        return tablaResultado;
        //return new DefaultTableModel(data, columnNames);
        
        
    }
    private void pagarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarBTNMouseClicked
        // TODO add your handling code here:
        boolean continue_flag = false;
        try {   
            int imprimir = JOptionPane.showConfirmDialog(null, 
                    "¿Desea imprimir la factura?");
            
            if (imprimir == JOptionPane.YES_OPTION){
                int selectedPlanilla = Integer.valueOf(plaNumTextEdit.getText());
                
                //Frames.MainFrame.getQueryObject().updatePlanillas(selectedPlanilla);
                
                continue_flag = true;
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date        date = new Date();
            
                PDFprinter generatePDFFileIText = new PDFprinter();
                
                //getSelectedTable(jTablePlanillas,selectedPlanilla);
                generatePDFFileIText.createPDF(new File("GeneratePDFFileIText.pdf"),getSelectedTable(jTablePlanillas,selectedPlanilla));
                //generatePDFFileIText.createPDF(new File("factura" + dateFormat.format(date) + ".pdf"), jTablePlanillas, selectedPlanilla);
                //jTablePlanillas.get
            }
            else{}
       
        }catch (Exception e) {
            System.err.println(e);
        }
        /*
        if (continue_flag) {
            ResultSet rs = MainFrame.getQueryObject().getPlanillas();
            try{
               jTablePlanillas.setModel(EmpPlantaDialog.buildTableModel(rs));
               revalidate();
              repaint();
            }
            catch(Exception e){
                System.err.println(e.getMessage());
            }
            finally{
                util.DBConnection.getInstance().disconnect();
                
            }
        }*/
        
    }//GEN-LAST:event_pagarBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosPlanillasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosPlanillasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosPlanillasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosPlanillasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagosPlanillasDialog dialog = new PagosPlanillasDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void fillTable(){
        //System.out.println(Type);
        
               
            ResultSet rs = MainFrame.getQueryObject().getPlanillas();

            try{
               jTablePlanillas.setModel(EmpPlantaDialog.buildTableModel(rs));
            }
            catch(Exception e){
                //System.out.println("Nop");
                System.err.println(e.getMessage());
            }
            finally{
                util.DBConnection.getInstance().disconnect();
            }
        
    }

    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {
       
        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();

        while (rs.next()) {
            //System.out.println("Jjeje");
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPagosBTN;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePlanillas;
    private javax.swing.JButton pagarBTN;
    private javax.swing.JTextField plaNumTextEdit;
    // End of variables declaration//GEN-END:variables
}
